### ISSUE TITLE
iOS13中，statusBar訪問寫法 | LazyBlog

### ISSUE THREAD

**Issue by League2EB** [League2EB/LazyBlog#2]
https://ios.league2eb.me/posts/216bbda6/ 

 可以說是一個筆記本

**Comment by League2EB** [comment]
WTF

**Comment by XuanCiTech** [comment]
WTF

**Comment by luoyunchong** [comment]
11

**Comment by luoyunchong** [comment]
everythings is ok??




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"XuanCiTech"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月4日(星期四) 下午4:08
收件人:&nbsp;"League2EB/LazyBlog"<LazyBlog@noreply.github.com&gt;;
抄送:&nbsp;"罗志强"<luoyunchong@foxmail.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [League2EB/LazyBlog] iOS13中，statusBar訪問寫法 | LazyBlog (#2)





 
WTF

**Comment by luoyunchong** [comment]
用github登录一下就好了?🤣

**Comment by League2EB** [comment]
我发现解决方法了
就是先登入自己的github帐号，然后写一则评论 就开通了...

**Comment by hirakujira** [comment]
'OR'1'='1'--
